name = "image-background-remover"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
REMOVE_BG_API_KEY = "QqhFaNyAce2QwYzm7m82MUyR"
NEXT_PUBLIC_PAYPAL_CLIENT_ID = "AZ1p5M9Y9yMmqcIn8U4jgFDHyRM9wR_jFb7VAx0yFhp8FAuuQmifwhj7CRIpVPkD6pBtWhAS5ByN9kjk"
PAYPAL_CLIENT_ID = "AZ1p5M9Y9yMmqcIn8U4jgFDHyRM9wR_jFb7VAx0yFhp8FAuuQmifwhj7CRIpVPkD6pBtWhAS5ByN9kjk"
PAYPAL_SECRET = "EHCMfVzsFRzC9JnCZ5k0c7mKUuBVubsP35UpOUCKPskCqZnzcHjtWRfOc0Nt0GmZ6A8yPNckxeSDvghk"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "task-database"
database_id = "c992aed2-c495-4302-95c6-4ef88eeee220"
