name = "image-background-remover"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
REMOVE_BG_API_KEY = "QqhFaNyAce2QwYzm7m82MUyR"
NEXT_PUBLIC_PAYPAL_CLIENT_ID = "Ae316YOk6i3rlT2YrFNBbjoLcMCC3j9uJYJqohQSYA9ObqZqoxpdtDIP2IWbnZMo9g0HD278u7LmJKdU"
PAYPAL_CLIENT_ID = "Ae316YOk6i3rlT2YrFNBbjoLcMCC3j9uJYJqohQSYA9ObqZqoxpdtDIP2IWbnZMo9g0HD278u7LmJKdU"
PAYPAL_SECRET = "EB4qwa7WUtOBlk85O6qMeUJuAdjuemmU7TD8Pq8l9HnCuFdGSKpOCCsCGACWSs2a0DR_nk8lYbS-pWtY"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "task-database"
database_id = "c992aed2-c495-4302-95c6-4ef88eeee220"
